const FLAG_EMOJI: Record<string, string> = {
  /* ── América do Sul ── */
  'Brazil': '🇧🇷', 'Brasil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Colombia': '🇨🇴', 'Colômbia': '🇨🇴',
  'Uruguay': '🇺🇾', 'Uruguai': '🇺🇾',
  'Ecuador': '🇪🇨', 'Equador': '🇪🇨',
  'Venezuela': '🇻🇪',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Paraguay': '🇵🇾', 'Paraguai': '🇵🇾',
  'Bolivia': '🇧🇴', 'Bolívia': '🇧🇴',

  /* ── América do Norte / Central / Caribe ── */
  'USA': '🇺🇸', 'United States': '🇺🇸', 'Estados Unidos': '🇺🇸',
  'Mexico': '🇲🇽', 'México': '🇲🇽',
  'Canada': '🇨🇦', 'Canadá': '🇨🇦',
  'Panama': '🇵🇦', 'Panamá': '🇵🇦',
  'Costa Rica': '🇨🇷',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'El Salvador': '🇸🇻',
  'Guatemala': '🇬🇹',
  'Haiti': '🇭🇹',
  'Cuba': '🇨🇺',
  'Trinidad and Tobago': '🇹🇹', 'Trinidad e Tobago': '🇹🇹',
  'Curaçao': '🇨🇼',

  /* ── Europa ── */
  'France': '🇫🇷', 'França': '🇫🇷',
  'Germany': '🇩🇪', 'Alemanha': '🇩🇪',
  'Spain': '🇪🇸', 'Espanha': '🇪🇸',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱', 'Holanda': '🇳🇱', 'Países Baixos': '🇳🇱',
  'Belgium': '🇧🇪', 'Bélgica': '🇧🇪',
  'Italy': '🇮🇹', 'Itália': '🇮🇹',
  'Croatia': '🇭🇷', 'Croácia': '🇭🇷',
  'Switzerland': '🇨🇭', 'Suíça': '🇨🇭',
  'Denmark': '🇩🇰', 'Dinamarca': '🇩🇰',
  'Sweden': '🇸🇪', 'Suécia': '🇸🇪',
  'Norway': '🇳🇴', 'Noruega': '🇳🇴',
  'Poland': '🇵🇱', 'Polônia': '🇵🇱',
  'Ukraine': '🇺🇦', 'Ucrânia': '🇺🇦',
  'Serbia': '🇷🇸', 'Sérvia': '🇷🇸',
  'Austria': '🇦🇹',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Escócia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Turkey': '🇹🇷', 'Turquia': '🇹🇷',
  'Slovakia': '🇸🇰', 'Eslováquia': '🇸🇰',
  'Czech Republic': '🇨🇿', 'República Tcheca': '🇨🇿', 'Tchéquia': '🇨🇿', 'Czechia': '🇨🇿',
  'Hungary': '🇭🇺', 'Hungria': '🇭🇺',
  'Greece': '🇬🇷', 'Grécia': '🇬🇷',
  'Romania': '🇷🇴', 'Romênia': '🇷🇴',
  'Bosnia and Herzegovina': '🇧🇦', 'Bósnia e Herzegovina': '🇧🇦', 'Bósnia-Herzegovina': '🇧🇦', 'Bosnia & Herzegovina': '🇧🇦',
  'Albania': '🇦🇱', 'Albânia': '🇦🇱',
  'Slovenia': '🇸🇮', 'Eslovênia': '🇸🇮',
  'Finland': '🇫🇮', 'Finlândia': '🇫🇮',
  'North Macedonia': '🇲🇰', 'Macedônia do Norte': '🇲🇰',
  'Russia': '🇷🇺', 'Rússia': '🇷🇺',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'País de Gales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Iceland': '🇮🇸', 'Islândia': '🇮🇸',
  'Ireland': '🇮🇪', 'Irlanda': '🇮🇪',
  'Kosovo': '🇽🇰',

  /* ── África ── */
  'Morocco': '🇲🇦', 'Marrocos': '🇲🇦',
  'Senegal': '🇸🇳',
  'Nigeria': '🇳🇬', 'Nigéria': '🇳🇬',
  'Cameroon': '🇨🇲', 'Camarões': '🇨🇲',
  'Ghana': '🇬🇭',
  'Egypt': '🇪🇬', 'Egito': '🇪🇬',
  'Ivory Coast': '🇨🇮', 'Costa do Marfim': '🇨🇮',
  'South Africa': '🇿🇦', 'África do Sul': '🇿🇦',
  'Mali': '🇲🇱',
  'Algeria': '🇩🇿', 'Argélia': '🇩🇿',
  'Tunisia': '🇹🇳', 'Tunísia': '🇹🇳',
  'Tanzania': '🇹🇿', 'Tanzânia': '🇹🇿',
  'Angola': '🇦🇴',
  'DR Congo': '🇨🇩', 'Congo': '🇨🇬', 'República Democrática do Congo': '🇨🇩',
  'Guinea': '🇬🇳', 'Guiné': '🇬🇳',
  'Equatorial Guinea': '🇬🇶', 'Guiné Equatorial': '🇬🇶',
  'Cape Verde': '🇨🇻', 'Cabo Verde': '🇨🇻',
  'Gambia': '🇬🇲', 'Gâmbia': '🇬🇲',
  'Uganda': '🇺🇬',
  'Zambia': '🇿🇲', 'Zâmbia': '🇿🇲',
  'Mozambique': '🇲🇿', 'Moçambique': '🇲🇿',
  'Kenya': '🇰🇪', 'Quênia': '🇰🇪',
  'Ethiopia': '🇪🇹', 'Etiópia': '🇪🇹',
  'Libya': '🇱🇾', 'Líbia': '🇱🇾',
  'Comoros': '🇰🇲', 'Comores': '🇰🇲',

  /* ── Ásia ── */
  'Japan': '🇯🇵', 'Japão': '🇯🇵',
  'South Korea': '🇰🇷', 'Coreia do Sul': '🇰🇷',
  'Australia': '🇦🇺', 'Austrália': '🇦🇺',
  'Iran': '🇮🇷', 'Irã': '🇮🇷',
  'Saudi Arabia': '🇸🇦', 'Arábia Saudita': '🇸🇦',
  'Qatar': '🇶🇦',
  'China': '🇨🇳',
  'Indonesia': '🇮🇩', 'Indonésia': '🇮🇩',
  'Iraq': '🇮🇶', 'Iraque': '🇮🇶',
  'UAE': '🇦🇪', 'United Arab Emirates': '🇦🇪', 'Emirados Árabes': '🇦🇪', 'Emirados Árabes Unidos': '🇦🇪',
  'Uzbekistan': '🇺🇿', 'Uzbequistão': '🇺🇿',
  'Kyrgyzstan': '🇰🇬', 'Quirguistão': '🇰🇬',
  'Tajikistan': '🇹🇯', 'Tajiquistão': '🇹🇯',
  'Oman': '🇴🇲', 'Omã': '🇴🇲',
  'Jordan': '🇯🇴', 'Jordânia': '🇯🇴',
  'Kuwait': '🇰🇼',
  'Bahrain': '🇧🇭', 'Bahrein': '🇧🇭',
  'Thailand': '🇹🇭', 'Tailândia': '🇹🇭',
  'Vietnam': '🇻🇳', 'Vietnã': '🇻🇳',
  'Palestine': '🇵🇸', 'Palestina': '🇵🇸',
  'Azerbaijan': '🇦🇿', 'Azerbaijão': '🇦🇿',

  /* ── Oceania ── */
  'New Zealand': '🇳🇿', 'Nova Zelândia': '🇳🇿',
  'Fiji': '🇫🇯',
  'Papua New Guinea': '🇵🇬', 'Papua Nova Guiné': '🇵🇬',
  'Solomon Islands': '🇸🇧', 'Ilhas Salomão': '🇸🇧',
  'Tahiti': '🇵🇫', 'Taiti': '🇵🇫',
  'New Caledonia': '🇳🇨', 'Nova Caledônia': '🇳🇨',
};

export function getFlag(teamName: string, flagUrl?: string | null): string {
  if (flagUrl) return flagUrl;
  return FLAG_EMOJI[teamName] ?? '⬜';
}

export function isEmojiFlag(flag: string): boolean {
  return !flag.startsWith('http');
}

const COUNTRY_CODES: Record<string, string> = {
  /* América do Sul */
  'Brazil': 'BRA', 'Brasil': 'BRA',
  'Argentina': 'ARG',
  'Colombia': 'COL', 'Colômbia': 'COL',
  'Uruguay': 'URU', 'Uruguai': 'URU',
  'Ecuador': 'ECU', 'Equador': 'ECU',
  'Venezuela': 'VEN',
  'Chile': 'CHI',
  'Peru': 'PER',
  'Paraguay': 'PAR', 'Paraguai': 'PAR',
  'Bolivia': 'BOL', 'Bolívia': 'BOL',
  /* América do Norte / Central */
  'USA': 'USA', 'United States': 'USA', 'Estados Unidos': 'USA',
  'Mexico': 'MEX', 'México': 'MEX',
  'Canada': 'CAN', 'Canadá': 'CAN',
  'Panama': 'PAN', 'Panamá': 'PAN',
  'Costa Rica': 'CRC',
  'Honduras': 'HON',
  'Jamaica': 'JAM',
  'El Salvador': 'SLV',
  'Guatemala': 'GUA',
  'Haiti': 'HAI',
  'Trinidad and Tobago': 'TRI', 'Trinidad e Tobago': 'TRI',
  /* Europa */
  'France': 'FRA', 'França': 'FRA',
  'Germany': 'GER', 'Alemanha': 'GER',
  'Spain': 'ESP', 'Espanha': 'ESP',
  'England': 'ENG', 'Inglaterra': 'ENG',
  'Portugal': 'POR',
  'Netherlands': 'NED', 'Holanda': 'NED', 'Países Baixos': 'NED',
  'Belgium': 'BEL', 'Bélgica': 'BEL',
  'Italy': 'ITA', 'Itália': 'ITA',
  'Croatia': 'CRO', 'Croácia': 'CRO',
  'Switzerland': 'SUI', 'Suíça': 'SUI',
  'Denmark': 'DEN', 'Dinamarca': 'DEN',
  'Sweden': 'SWE', 'Suécia': 'SWE',
  'Norway': 'NOR', 'Noruega': 'NOR',
  'Poland': 'POL', 'Polônia': 'POL',
  'Ukraine': 'UKR', 'Ucrânia': 'UKR',
  'Serbia': 'SRB', 'Sérvia': 'SRB',
  'Austria': 'AUT',
  'Scotland': 'SCO', 'Escócia': 'SCO',
  'Turkey': 'TUR', 'Turquia': 'TUR',
  'Slovakia': 'SVK', 'Eslováquia': 'SVK',
  'Czech Republic': 'CZE', 'República Tcheca': 'CZE', 'Tchéquia': 'CZE', 'Czechia': 'CZE',
  'Hungary': 'HUN', 'Hungria': 'HUN',
  'Greece': 'GRE', 'Grécia': 'GRE',
  'Romania': 'ROU', 'Romênia': 'ROU',
  'Wales': 'WAL', 'País de Gales': 'WAL',
  'Russia': 'RUS', 'Rússia': 'RUS',
  /* África */
  'Morocco': 'MAR', 'Marrocos': 'MAR',
  'Senegal': 'SEN',
  'Nigeria': 'NGA', 'Nigéria': 'NGA',
  'Cameroon': 'CMR', 'Camarões': 'CMR',
  'Ghana': 'GHA',
  'Egypt': 'EGY', 'Egito': 'EGY',
  'Ivory Coast': 'CIV', 'Costa do Marfim': 'CIV',
  'South Africa': 'RSA', 'África do Sul': 'RSA',
  'Algeria': 'ALG', 'Argélia': 'ALG',
  'Tunisia': 'TUN', 'Tunísia': 'TUN',
  /* Ásia */
  'Japan': 'JPN', 'Japão': 'JPN',
  'South Korea': 'KOR', 'Coreia do Sul': 'KOR',
  'Australia': 'AUS', 'Austrália': 'AUS',
  'Iran': 'IRN', 'Irã': 'IRN',
  'Saudi Arabia': 'KSA', 'Arábia Saudita': 'KSA',
  'Qatar': 'QAT',
  'China': 'CHN',
  'Indonesia': 'IDN', 'Indonésia': 'IDN',
  'Iraq': 'IRQ', 'Iraque': 'IRQ',
  'UAE': 'UAE', 'United Arab Emirates': 'UAE', 'Emirados Árabes': 'UAE', 'Emirados Árabes Unidos': 'UAE',
  /* Oceania */
  'New Zealand': 'NZL', 'Nova Zelândia': 'NZL',
};

export function getCountryCode(teamName: string): string {
  return COUNTRY_CODES[teamName] ?? teamName.slice(0, 3).toUpperCase();
}
