const FLAG_EMOJI: Record<string, string> = {
  /* ── América do Sul ── */
  'Brazil': '🇧🇷', 'Brasil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Colombia': '🇨🇴', 'Colômbia': '🇨🇴',
  'Uruguay': '🇺🇾', 'Uruguai': '🇺🇾',
  'Ecuador': '🇪🇨', 'Equador': '🇪🇨',
  'Venezuela': '🇻🇪',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Paraguay': '🇵🇾', 'Paraguai': '🇵🇾',
  'Bolivia': '🇧🇴', 'Bolívia': '🇧🇴',

  /* ── América do Norte / Central / Caribe ── */
  'USA': '🇺🇸', 'United States': '🇺🇸', 'Estados Unidos': '🇺🇸',
  'Mexico': '🇲🇽', 'México': '🇲🇽',
  'Canada': '🇨🇦', 'Canadá': '🇨🇦',
  'Panama': '🇵🇦', 'Panamá': '🇵🇦',
  'Costa Rica': '🇨🇷',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'El Salvador': '🇸🇻',
  'Guatemala': '🇬🇹',
  'Haiti': '🇭🇹',
  'Cuba': '🇨🇺',
  'Trinidad and Tobago': '🇹🇹', 'Trinidad e Tobago': '🇹🇹',
  'Curaçao': '🇨🇼',

  /* ── Europa ── */
  'France': '🇫🇷', 'França': '🇫🇷',
  'Germany': '🇩🇪', 'Alemanha': '🇩🇪',
  'Spain': '🇪🇸', 'Espanha': '🇪🇸',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱', 'Holanda': '🇳🇱', 'Países Baixos': '🇳🇱',
  'Belgium': '🇧🇪', 'Bélgica': '🇧🇪',
  'Italy': '🇮🇹', 'Itália': '🇮🇹',
  'Croatia': '🇭🇷', 'Croácia': '🇭🇷',
  'Switzerland': '🇨🇭', 'Suíça': '🇨🇭',
  'Denmark': '🇩🇰', 'Dinamarca': '🇩🇰',
  'Sweden': '🇸🇪', 'Suécia': '🇸🇪',
  'Norway': '🇳🇴', 'Noruega': '🇳🇴',
  'Poland': '🇵🇱', 'Polônia': '🇵🇱',
  'Ukraine': '🇺🇦', 'Ucrânia': '🇺🇦',
  'Serbia': '🇷🇸', 'Sérvia': '🇷🇸',
  'Austria': '🇦🇹',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Escócia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Turkey': '🇹🇷', 'Turquia': '🇹🇷',
  'Slovakia': '🇸🇰', 'Eslováquia': '🇸🇰',
  'Czech Republic': '🇨🇿', 'República Tcheca': '🇨🇿', 'Tchéquia': '🇨🇿', 'Czechia': '🇨🇿',
  'Hungary': '🇭🇺', 'Hungria': '🇭🇺',
  'Greece': '🇬🇷', 'Grécia': '🇬🇷',
  'Romania': '🇷🇴', 'Romênia': '🇷🇴',
  'Bosnia and Herzegovina': '🇧🇦', 'Bósnia e Herzegovina': '🇧🇦', 'Bósnia-Herzegovina': '🇧🇦', 'Bosnia & Herzegovina': '🇧🇦',
  'Albania': '🇦🇱', 'Albânia': '🇦🇱',
  'Slovenia': '🇸🇮', 'Eslovênia': '🇸🇮',
  'Finland': '🇫🇮', 'Finlândia': '🇫🇮',
  'North Macedonia': '🇲🇰', 'Macedônia do Norte': '🇲🇰',
  'Russia': '🇷🇺', 'Rússia': '🇷🇺',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'País de Gales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Iceland': '🇮🇸', 'Islândia': '🇮🇸',
  'Ireland': '🇮🇪', 'Irlanda': '🇮🇪',
  'Kosovo': '🇽🇰',

  /* ── África ── */
  'Morocco': '🇲🇦', 'Marrocos': '🇲🇦',
  'Senegal': '🇸🇳',
  'Nigeria': '🇳🇬', 'Nigéria': '🇳🇬',
  'Cameroon': '🇨🇲', 'Camarões': '🇨🇲',
  'Ghana': '🇬🇭',
  'Egypt': '🇪🇬', 'Egito': '🇪🇬',
  'Ivory Coast': '🇨🇮', 'Costa do Marfim': '🇨🇮',
  'South Africa': '🇿🇦', 'África do Sul': '🇿🇦',
  'Mali': '🇲🇱',
  'Algeria': '🇩🇿', 'Argélia': '🇩🇿',
  'Tunisia': '🇹🇳', 'Tunísia': '🇹🇳',
  'Tanzania': '🇹🇿', 'Tanzânia': '🇹🇿',
  'Angola': '🇦🇴',
  'DR Congo': '🇨🇩', 'Congo': '🇨🇬', 'República Democrática do Congo': '🇨🇩',
  'Guinea': '🇬🇳', 'Guiné': '🇬🇳',
  'Equatorial Guinea': '🇬🇶', 'Guiné Equatorial': '🇬🇶',
  'Cape Verde': '🇨🇻', 'Cabo Verde': '🇨🇻',
  'Gambia': '🇬🇲', 'Gâmbia': '🇬🇲',
  'Uganda': '🇺🇬',
  'Zambia': '🇿🇲', 'Zâmbia': '🇿🇲',
  'Mozambique': '🇲🇿', 'Moçambique': '🇲🇿',
  'Kenya': '🇰🇪', 'Quênia': '🇰🇪',
  'Ethiopia': '🇪🇹', 'Etiópia': '🇪🇹',
  'Libya': '🇱🇾', 'Líbia': '🇱🇾',
  'Comoros': '🇰🇲', 'Comores': '🇰🇲',

  /* ── Ásia ── */
  'Japan': '🇯🇵', 'Japão': '🇯🇵',
  'South Korea': '🇰🇷', 'Coreia do Sul': '🇰🇷',
  'Australia': '🇦🇺', 'Austrália': '🇦🇺',
  'Iran': '🇮🇷', 'Irã': '🇮🇷',
  'Saudi Arabia': '🇸🇦', 'Arábia Saudita': '🇸🇦',
  'Qatar': '🇶🇦',
  'China': '🇨🇳',
  'Indonesia': '🇮🇩', 'Indonésia': '🇮🇩',
  'Iraq': '🇮🇶', 'Iraque': '🇮🇶',
  'UAE': '🇦🇪', 'United Arab Emirates': '🇦🇪', 'Emirados Árabes': '🇦🇪', 'Emirados Árabes Unidos': '🇦🇪',
  'Uzbekistan': '🇺🇿', 'Uzbequistão': '🇺🇿',
  'Kyrgyzstan': '🇰🇬', 'Quirguistão': '🇰🇬',
  'Tajikistan': '🇹🇯', 'Tajiquistão': '🇹🇯',
  'Oman': '🇴🇲', 'Omã': '🇴🇲',
  'Jordan': '🇯🇴', 'Jordânia': '🇯🇴',
  'Kuwait': '🇰🇼',
  'Bahrain': '🇧🇭', 'Bahrein': '🇧🇭',
  'Thailand': '🇹🇭', 'Tailândia': '🇹🇭',
  'Vietnam': '🇻🇳', 'Vietnã': '🇻🇳',
  'Palestine': '🇵🇸', 'Palestina': '🇵🇸',
  'Azerbaijan': '🇦🇿', 'Azerbaijão': '🇦🇿',

  /* ── Oceania ── */
  'New Zealand': '🇳🇿', 'Nova Zelândia': '🇳🇿',
  'Fiji': '🇫🇯',
  'Papua New Guinea': '🇵🇬', 'Papua Nova Guiné': '🇵🇬',
  'Solomon Islands': '🇸🇧', 'Ilhas Salomão': '🇸🇧',
  'Tahiti': '🇵🇫', 'Taiti': '🇵🇫',
  'New Caledonia': '🇳🇨', 'Nova Caledônia': '🇳🇨',
};

export function getFlag(teamName: string, flagUrl?: string | null): string {
  if (flagUrl) return flagUrl;
  return FLAG_EMOJI[teamName] ?? '⬜';
}

export function isEmojiFlag(flag: string): boolean {
  return !flag.startsWith('http');
}
